# Generated by Django 4.0.3 on 2022-04-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
