# Generated by Django 4.0.4 on 2022-04-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categroy',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
