# Generated by Django 4.0.6 on 2022-07-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(default='', upload_to='images/products/')),
                ('desc', models.TextField()),
                ('stocks', models.PositiveIntegerField(default=1)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tryapp.seller')),
            ],
        ),
    ]
