# Generated by Django 4.0.6 on 2022-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0005_alter_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('J', 'JEANS'), ('TW', 'TOPWEAR'), ('M', 'MOBILE')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
