# Generated by Django 4.0.6 on 2022-08-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0006_products_category_alter_products_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('J', 'Jeans'), ('TW', 'Top Wear'), ('M', 'Mobile')], default='', max_length=4),
        ),
    ]
